# Generated by Django 2.1.2 on 2018-10-22 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sandesh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='Gender',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='PhoneNo',
            field=models.IntegerField(),
        ),
    ]
